window._printTemplateData = {
  "version": 2,
  "layouts": {
    "1": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 250
        }
      ],
      "elements": [
        {
          "id": "e1",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 122.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e2",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 127.5,
          "w": 200,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 134.5,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e4",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 13,
          "y": 139.9,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 105,
          "y": 134.5,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e6",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 105,
          "y": 139.9,
          "w": 92,
          "h": 7.7,
          "fontSize": 18.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e7",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 163.3,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e8",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 13,
          "y": 168.7,
          "w": 15,
          "h": 15,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e9",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 31,
          "y": 173.2,
          "w": 74,
          "h": 6.6,
          "fontSize": 12,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 105,
          "y": 163.3,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e11",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 105,
          "y": 168.7,
          "w": 15,
          "h": 15,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e12",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 123,
          "y": 173.2,
          "w": 74,
          "h": 6.6,
          "fontSize": 12,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e13",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 191.1,
          "w": 184,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 197,
          "w": 96.6,
          "h": 26.8,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 16,
          "y": 201.3,
          "w": 90.6,
          "h": 3.6,
          "fontSize": 7,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e16",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 16,
          "y": 210.4,
          "w": 90.6,
          "h": 6.6,
          "fontSize": 11,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e19",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 229.8,
          "w": 200,
          "h": 24.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e20",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 229.8,
          "w": 200,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 234.6,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e22",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": 0,
          "x": 13,
          "y": 241.9,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e23",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 105,
          "y": 234.6,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e24",
          "type": "field",
          "field": "total",
          "cardIndex": 0,
          "x": 105,
          "y": 241.2,
          "w": 92,
          "h": 10.2,
          "fontSize": 17,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        }
      ]
    },
    "2": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 97.5,
          "h": 150
        },
        {
          "x": 107.5,
          "y": 5,
          "w": 97.5,
          "h": 150
        }
      ],
      "elements": [
        {
          "id": "e1",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 97.5,
          "h": 81,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e2",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 86,
          "w": 97.5,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 8.9,
          "y": 91.3,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e4",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 8.9,
          "y": 95.6,
          "w": 44.9,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 53.8,
          "y": 91.3,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e6",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 53.8,
          "y": 95.6,
          "w": 44.9,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e7",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 8.9,
          "y": 110.8,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e8",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 8.9,
          "y": 115.1,
          "w": 12.1,
          "h": 12.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e9",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 24,
          "y": 118.7,
          "w": 29.8,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 53.8,
          "y": 110.8,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e11",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 53.8,
          "y": 115.1,
          "w": 12.1,
          "h": 12.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e12",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 68.9,
          "y": 118.7,
          "w": 29.8,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e13",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 8.9,
          "y": 129.5,
          "w": 89.7,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 8.9,
          "y": 133.6,
          "w": 47.1,
          "h": 18.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 11.9,
          "y": 136.5,
          "w": 41.1,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e16",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 11.9,
          "y": 142.7,
          "w": 41.1,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e19",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 107.5,
          "y": 5,
          "w": 97.5,
          "h": 81,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e20",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 107.5,
          "y": 86,
          "w": 97.5,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 111.4,
          "y": 91.3,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e22",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 111.4,
          "y": 95.6,
          "w": 44.9,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e23",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 156.3,
          "y": 91.3,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e24",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 156.3,
          "y": 95.6,
          "w": 44.9,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e25",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 111.4,
          "y": 110.8,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e26",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 111.4,
          "y": 115.1,
          "w": 12.1,
          "h": 12.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e27",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 126.5,
          "y": 118.7,
          "w": 29.8,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e28",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 156.3,
          "y": 110.8,
          "w": 44.9,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e29",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 156.3,
          "y": 115.1,
          "w": 12.1,
          "h": 12.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e30",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 171.4,
          "y": 118.7,
          "w": 29.8,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e31",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 111.4,
          "y": 129.5,
          "w": 89.7,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e32",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 111.4,
          "y": 133.6,
          "w": 47.1,
          "h": 18.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e33",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 114.4,
          "y": 136.5,
          "w": 41.1,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e34",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 114.4,
          "y": 142.7,
          "w": 41.1,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e37",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 159,
          "w": 200,
          "h": 24,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e38",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 159,
          "w": 200,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e39",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 58,
          "y": 164.3,
          "w": 55,
          "h": 4.5,
          "fontSize": 9,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e40",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": -1,
          "x": 58,
          "y": 171.5,
          "w": 55,
          "h": 7,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e41",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 120,
          "y": 164.3,
          "w": 82,
          "h": 4.5,
          "fontSize": 9,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e42",
          "type": "field",
          "field": "total",
          "cardIndex": -1,
          "x": 120,
          "y": 170.8,
          "w": 82,
          "h": 11,
          "fontSize": 18,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        }
      ]
    },
    "3": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 63.3,
          "h": 140
        },
        {
          "x": 73.3,
          "y": 5,
          "w": 63.3,
          "h": 140
        },
        {
          "x": 141.6,
          "y": 5,
          "w": 63.3,
          "h": 140
        }
      ],
      "elements": [
        {
          "id": "e1",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 63.3,
          "h": 75.6,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e2",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 80.6,
          "w": 63.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 7.5,
          "y": 85.7,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e4",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 7.5,
          "y": 90,
          "w": 29.1,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 36.6,
          "y": 85.7,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e6",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 36.6,
          "y": 90,
          "w": 29.1,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e7",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 7.5,
          "y": 103.8,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e8",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 7.5,
          "y": 108.1,
          "w": 11.2,
          "h": 11.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e9",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 21.7,
          "y": 111.5,
          "w": 14.9,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 36.6,
          "y": 103.8,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e11",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 36.6,
          "y": 108.1,
          "w": 11.2,
          "h": 11.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e12",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 50.8,
          "y": 111.5,
          "w": 14.9,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e13",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 7.5,
          "y": 121.3,
          "w": 58.3,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 7.5,
          "y": 125,
          "w": 30.6,
          "h": 16.8,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 10.5,
          "y": 127.7,
          "w": 24.6,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e16",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 10.5,
          "y": 133.4,
          "w": 24.6,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e19",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 73.3,
          "y": 5,
          "w": 63.3,
          "h": 75.6,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e20",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 73.3,
          "y": 80.6,
          "w": 63.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 75.8,
          "y": 85.7,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e22",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 75.8,
          "y": 90,
          "w": 29.1,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e23",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 104.9,
          "y": 85.7,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e24",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 104.9,
          "y": 90,
          "w": 29.1,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e25",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 75.8,
          "y": 103.8,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e26",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 75.8,
          "y": 108.1,
          "w": 11.2,
          "h": 11.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e27",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 90,
          "y": 111.5,
          "w": 14.9,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e28",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 104.9,
          "y": 103.8,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e29",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 104.9,
          "y": 108.1,
          "w": 11.2,
          "h": 11.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e30",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 119.1,
          "y": 111.5,
          "w": 14.9,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e31",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 75.8,
          "y": 121.3,
          "w": 58.3,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e32",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 75.8,
          "y": 125,
          "w": 30.6,
          "h": 16.8,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e33",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 78.8,
          "y": 127.7,
          "w": 24.6,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e34",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 78.8,
          "y": 133.4,
          "w": 24.6,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e37",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 141.6,
          "y": 5,
          "w": 63.3,
          "h": 75.6,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e38",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 141.6,
          "y": 80.6,
          "w": 63.3,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e39",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 144.1,
          "y": 85.7,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e40",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 2,
          "x": 144.1,
          "y": 90,
          "w": 29.1,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e41",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 173.2,
          "y": 85.7,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e42",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 173.2,
          "y": 90,
          "w": 29.1,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e43",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 144.1,
          "y": 103.8,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e44",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 144.1,
          "y": 108.1,
          "w": 11.2,
          "h": 11.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e45",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 158.3,
          "y": 111.5,
          "w": 14.9,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e46",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 173.2,
          "y": 103.8,
          "w": 29.1,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e47",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 173.2,
          "y": 108.1,
          "w": 11.2,
          "h": 11.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e48",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 187.4,
          "y": 111.5,
          "w": 14.9,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e49",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 144.1,
          "y": 121.3,
          "w": 58.3,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e50",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 144.1,
          "y": 125,
          "w": 30.6,
          "h": 16.8,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e51",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 147.1,
          "y": 127.7,
          "w": 24.6,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e52",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 147.1,
          "y": 133.4,
          "w": 24.6,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e55",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 149,
          "w": 200,
          "h": 24,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e56",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 149,
          "w": 200,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e57",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 58,
          "y": 154.3,
          "w": 55,
          "h": 4.5,
          "fontSize": 9,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e58",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": -1,
          "x": 58,
          "y": 161.5,
          "w": 55,
          "h": 7,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e59",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 120,
          "y": 154.3,
          "w": 82,
          "h": 4.5,
          "fontSize": 9,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e60",
          "type": "field",
          "field": "total",
          "cardIndex": -1,
          "x": 120,
          "y": 160.8,
          "w": 82,
          "h": 11,
          "fontSize": 18,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        }
      ]
    },
    "4": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 46.2,
          "h": 134
        },
        {
          "x": 56.2,
          "y": 5,
          "w": 46.2,
          "h": 134
        },
        {
          "x": 107.4,
          "y": 5,
          "w": 46.2,
          "h": 134
        },
        {
          "x": 158.6,
          "y": 5,
          "w": 46.2,
          "h": 134
        }
      ],
      "elements": [
        {
          "id": "e1",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 46.2,
          "h": 72.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e2",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 77.4,
          "w": 46.2,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 6.8,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e4",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 6.8,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 28.1,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e6",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 28.1,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e7",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 6.8,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e8",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 6.8,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e9",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 20.5,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 28.1,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e11",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 28.1,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e12",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 41.8,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e13",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 6.8,
          "y": 116.4,
          "w": 42.6,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 6.8,
          "y": 119.9,
          "w": 22.4,
          "h": 16.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9.8,
          "y": 122.5,
          "w": 16.4,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e16",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 9.8,
          "y": 128,
          "w": 16.4,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e19",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 56.2,
          "y": 5,
          "w": 46.2,
          "h": 72.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e20",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 56.2,
          "y": 77.4,
          "w": 46.2,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 58,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e22",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 58,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e23",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 79.3,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e24",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 79.3,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e25",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 58,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e26",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 58,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e27",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 71.7,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e28",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 79.3,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e29",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 79.3,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e30",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 93,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e31",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 58,
          "y": 116.4,
          "w": 42.6,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e32",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 58,
          "y": 119.9,
          "w": 22.4,
          "h": 16.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e33",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 61,
          "y": 122.5,
          "w": 16.4,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e34",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 61,
          "y": 128,
          "w": 16.4,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e37",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 107.4,
          "y": 5,
          "w": 46.2,
          "h": 72.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e38",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 107.4,
          "y": 77.4,
          "w": 46.2,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e39",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 109.2,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e40",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 2,
          "x": 109.2,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e41",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 130.5,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e42",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 130.5,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e43",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 109.2,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e44",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 109.2,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e45",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 122.9,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e46",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 130.5,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e47",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 130.5,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e48",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 144.2,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e49",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 109.2,
          "y": 116.4,
          "w": 42.6,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e50",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 109.2,
          "y": 119.9,
          "w": 22.4,
          "h": 16.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e51",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 112.2,
          "y": 122.5,
          "w": 16.4,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e52",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 112.2,
          "y": 128,
          "w": 16.4,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e55",
          "type": "image3d",
          "field": null,
          "cardIndex": 3,
          "x": 158.6,
          "y": 5,
          "w": 46.2,
          "h": 72.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e56",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 158.6,
          "y": 77.4,
          "w": 46.2,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e57",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 160.4,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e58",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 3,
          "x": 160.4,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e59",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 181.7,
          "y": 82.4,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e60",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 3,
          "x": 181.7,
          "y": 86.7,
          "w": 21.3,
          "h": 4.4,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e61",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 160.4,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e62",
          "type": "colorSwatch",
          "field": "sideColor",
          "cardIndex": 3,
          "x": 160.4,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e63",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 3,
          "x": 174.1,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e64",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 181.7,
          "y": 99.7,
          "w": 21.3,
          "h": 3,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e65",
          "type": "colorSwatch",
          "field": "shelfColor",
          "cardIndex": 3,
          "x": 181.7,
          "y": 104,
          "w": 10.7,
          "h": 10.7,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": "",
          "previewColorIdx": 0
        },
        {
          "id": "e66",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 3,
          "x": 195.4,
          "y": 107.2,
          "w": 7.6,
          "h": 3.9,
          "fontSize": 7,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e67",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 160.4,
          "y": 116.4,
          "w": 42.6,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e68",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 160.4,
          "y": 119.9,
          "w": 22.4,
          "h": 16.1,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e69",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 163.4,
          "y": 122.5,
          "w": 16.4,
          "h": 2.7,
          "fontSize": 6,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e70",
          "type": "field",
          "field": "code",
          "cardIndex": 3,
          "x": 163.4,
          "y": 128,
          "w": 16.4,
          "h": 4.8,
          "fontSize": 8,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e73",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 143,
          "w": 200,
          "h": 24,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e74",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 143,
          "w": 200,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e75",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 58,
          "y": 148.3,
          "w": 55,
          "h": 4.5,
          "fontSize": 9,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e76",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": -1,
          "x": 58,
          "y": 155.5,
          "w": 55,
          "h": 7,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e77",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 120,
          "y": 148.3,
          "w": 82,
          "h": 4.5,
          "fontSize": 9,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e78",
          "type": "field",
          "field": "total",
          "cardIndex": -1,
          "x": 120,
          "y": 154.8,
          "w": 82,
          "h": 11,
          "fontSize": 18,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        }
      ]
    }
  }
};
