window._printTemplateData = {
  "version": 2,
  "layouts": {
    "1": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 200,
          "h": 250
        }
      ],
      "elements": [
        {
          "id": "e1",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 204.2,
          "h": 155.8,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e2",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 160.3,
          "w": 200,
          "h": 0.5,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 14.400000000000006,
          "y": 165.7,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e4",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 14.400000000000006,
          "y": 172.9,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 85,
          "y": 165.20000000000002,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e6",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 113,
          "y": 172.9,
          "w": 92,
          "h": 7.7,
          "fontSize": 18.5,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e7",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 14.400000000000006,
          "y": 197.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e9",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 44.900000000000006,
          "y": 195.20000000000002,
          "w": 74,
          "h": 6.6,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e10",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 101.4,
          "y": 197.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e12",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 131,
          "y": 195.20000000000002,
          "w": 74,
          "h": 6.6,
          "fontSize": 12,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e13",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 209,
          "w": 184,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e14",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 212.2,
          "w": 80.6,
          "h": 11.6,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e15",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 14.400000000000006,
          "y": 216.70000000000002,
          "w": 90.6,
          "h": 3.6,
          "fontSize": 7,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e16",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 51.2,
          "y": 216.70000000000002,
          "w": 90.6,
          "h": 6.6,
          "fontSize": 11,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e19",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 229.8,
          "w": 200,
          "h": 24.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e20",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 229.8,
          "w": 200,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e21",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 13,
          "y": 234.6,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e22",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": 0,
          "x": 13,
          "y": 241.9,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e23",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 105,
          "y": 234.6,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e24",
          "type": "field",
          "field": "total",
          "cardIndex": 0,
          "x": 105,
          "y": 241.2,
          "w": 92,
          "h": 10.2,
          "fontSize": 17,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        }
      ]
    },
    "2": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 97.5,
          "h": 150
        },
        {
          "x": 107.5,
          "y": 5,
          "w": 97.5,
          "h": 150
        }
      ],
      "elements": [
        {
          "id": "e1",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 99.5,
          "h": 92.9,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e2",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 98.2,
          "w": 97.5,
          "h": 0.3,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e3",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9.6,
          "y": 101.4,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e4",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 9.6,
          "y": 105.7,
          "w": 44.9,
          "h": 4.3,
          "fontSize": 6.3,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e5",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 44,
          "y": 101.1,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e6",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 57.6,
          "y": 105.7,
          "w": 44.9,
          "h": 4.6,
          "fontSize": 9,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e7",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9.6,
          "y": 120.7,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e8",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 24.5,
          "y": 119.1,
          "w": 36.1,
          "h": 4,
          "fontSize": 5.8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e9",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 52,
          "y": 120.7,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e10",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 66.4,
          "y": 119.1,
          "w": 36.1,
          "h": 4,
          "fontSize": 5.8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e11",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 8.9,
          "y": 127.4,
          "w": 89.7,
          "h": 0.2,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e12",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 8.9,
          "y": 129.3,
          "w": 42.9,
          "h": 7,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e13",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 9.6,
          "y": 132,
          "w": 44.2,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e14",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 30.35,
          "y": 132,
          "w": 44.2,
          "h": 4,
          "fontSize": 5.4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e29",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 159,
          "w": 200,
          "h": 24.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e30",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 159,
          "w": 200,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e31",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 13,
          "y": 163.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e32",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": -1,
          "x": 13,
          "y": 171.1,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e33",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 105,
          "y": 163.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e34",
          "type": "field",
          "field": "total",
          "cardIndex": -1,
          "x": 105,
          "y": 170.4,
          "w": 92,
          "h": 10.2,
          "fontSize": 17,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e215",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 107.5,
          "y": 5,
          "w": 99.5,
          "h": 92.9,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e216",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 107.5,
          "y": 98.2,
          "w": 97.5,
          "h": 0.3,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e217",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112.1,
          "y": 101.4,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e218",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 112.1,
          "y": 105.7,
          "w": 44.9,
          "h": 4.3,
          "fontSize": 6.3,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e219",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 146.5,
          "y": 101.1,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e220",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 160.1,
          "y": 105.7,
          "w": 44.9,
          "h": 4.6,
          "fontSize": 9,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e221",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112.1,
          "y": 120.7,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e222",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 127,
          "y": 119.1,
          "w": 36.1,
          "h": 4,
          "fontSize": 5.8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e223",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 154.5,
          "y": 120.7,
          "w": 44.9,
          "h": 2.4,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e224",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 168.9,
          "y": 119.1,
          "w": 36.1,
          "h": 4,
          "fontSize": 5.8,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e225",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 111.4,
          "y": 127.4,
          "w": 89.7,
          "h": 0.2,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e226",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 111.4,
          "y": 129.3,
          "w": 42.9,
          "h": 7,
          "fontSize": 4.9,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e227",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 112.1,
          "y": 132,
          "w": 44.2,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e228",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 132.85,
          "y": 132,
          "w": 44.2,
          "h": 4,
          "fontSize": 5.4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    },
    "3": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 63.3,
          "h": 140
        },
        {
          "x": 73.3,
          "y": 5,
          "w": 63.3,
          "h": 140
        },
        {
          "x": 141.6,
          "y": 5,
          "w": 63.3,
          "h": 140
        }
      ],
      "elements": [
        {
          "id": "e35",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 64.6,
          "h": 87.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e36",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 92,
          "w": 63.3,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e37",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 8,
          "y": 95,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e38",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 8,
          "y": 99,
          "w": 29.1,
          "h": 4,
          "fontSize": 4.1,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e39",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 30.3,
          "y": 94.7,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e40",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 39.199999999999996,
          "y": 99,
          "w": 29.1,
          "h": 4.3,
          "fontSize": 5.9,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e41",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 8,
          "y": 111.5,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e42",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 18.300000000000004,
          "y": 115.2,
          "w": 23.4,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e43",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 36.6,
          "y": 111.5,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e44",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 44.85,
          "y": 115.2,
          "w": 23.4,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e45",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 7.5,
          "y": 119.2,
          "w": 58.2,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e46",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 7.5,
          "y": 121,
          "w": 39.7,
          "h": 6.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e47",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 8,
          "y": 123.6,
          "w": 28.7,
          "h": 2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e48",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 27.35,
          "y": 123.6,
          "w": 28.7,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e77",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 149,
          "w": 200,
          "h": 24.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e78",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 149,
          "w": 200,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e79",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 13,
          "y": 153.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e80",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": -1,
          "x": 13,
          "y": 161.1,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e81",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 105,
          "y": 153.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e82",
          "type": "field",
          "field": "total",
          "cardIndex": -1,
          "x": 105,
          "y": 160.4,
          "w": 92,
          "h": 10.2,
          "fontSize": 17,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e229",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 73.3,
          "y": 5,
          "w": 64.6,
          "h": 87.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e230",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 73.3,
          "y": 92,
          "w": 63.3,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e231",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 76.3,
          "y": 95,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e232",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 76.3,
          "y": 99,
          "w": 29.1,
          "h": 4,
          "fontSize": 4.1,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e233",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 98.6,
          "y": 94.7,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e234",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 107.5,
          "y": 99,
          "w": 29.1,
          "h": 4.3,
          "fontSize": 5.9,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e235",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 76.3,
          "y": 111.5,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e236",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 86.6,
          "y": 115.2,
          "w": 23.4,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e237",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 104.9,
          "y": 111.5,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e238",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 113.15,
          "y": 115.2,
          "w": 23.4,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e239",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 75.8,
          "y": 119.2,
          "w": 58.2,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e240",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 75.8,
          "y": 121,
          "w": 39.7,
          "h": 6.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e241",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 76.3,
          "y": 123.6,
          "w": 28.7,
          "h": 2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e242",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 95.65,
          "y": 123.6,
          "w": 28.7,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e243",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 141.6,
          "y": 5,
          "w": 64.6,
          "h": 87.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e244",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 141.6,
          "y": 92,
          "w": 63.3,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e245",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 144.6,
          "y": 95,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e246",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 2,
          "x": 144.6,
          "y": 99,
          "w": 29.1,
          "h": 4,
          "fontSize": 4.1,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e247",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 166.9,
          "y": 94.7,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e248",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 175.79999999999998,
          "y": 99,
          "w": 29.1,
          "h": 4.3,
          "fontSize": 5.9,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e249",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 144.6,
          "y": 111.5,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e250",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 154.9,
          "y": 115.2,
          "w": 23.4,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e251",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 173.2,
          "y": 111.5,
          "w": 29.1,
          "h": 2.2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e252",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 181.45,
          "y": 115.2,
          "w": 23.4,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e253",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 144.1,
          "y": 119.2,
          "w": 58.2,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e254",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 144.1,
          "y": 121,
          "w": 39.7,
          "h": 6.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e255",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 144.6,
          "y": 123.6,
          "w": 28.7,
          "h": 2,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e256",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 163.95,
          "y": 123.6,
          "w": 28.7,
          "h": 3.7,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    },
    "4": {
      "cards": [
        {
          "x": 5,
          "y": 5,
          "w": 46.2,
          "h": 134
        },
        {
          "x": 56.2,
          "y": 5,
          "w": 46.2,
          "h": 134
        },
        {
          "x": 107.4,
          "y": 5,
          "w": 46.2,
          "h": 134
        },
        {
          "x": 158.6,
          "y": 5,
          "w": 46.2,
          "h": 134
        }
      ],
      "elements": [
        {
          "id": "e83",
          "type": "image3d",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 5,
          "w": 47.2,
          "h": 83.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e84",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 5,
          "y": 88.2,
          "w": 46.2,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e85",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 7.2,
          "y": 91.1,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e86",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 0,
          "x": 7.2,
          "y": 95,
          "w": 21.3,
          "h": 3.9,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e87",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 23.5,
          "y": 90.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e88",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 0,
          "x": 29.9,
          "y": 95,
          "w": 21.3,
          "h": 4.1,
          "fontSize": 4.3,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e89",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 7.2,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e90",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 0,
          "x": 13,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e91",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 27.3,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e92",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 0,
          "x": 34.15,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e93",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 6.8,
          "y": 114.3,
          "w": 42.5,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e94",
          "type": "rect",
          "field": null,
          "cardIndex": 0,
          "x": 6.8,
          "y": 116.1,
          "w": 18.6,
          "h": 6.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e95",
          "type": "text",
          "field": null,
          "cardIndex": 0,
          "x": 7.2,
          "y": 118.5,
          "w": 20.9,
          "h": 1.9,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e96",
          "type": "field",
          "field": "code",
          "cardIndex": 0,
          "x": 27.3,
          "y": 119.45,
          "w": 20.9,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e139",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 143,
          "w": 200,
          "h": 24.2,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f9fafb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e140",
          "type": "rect",
          "field": null,
          "cardIndex": -1,
          "x": 5,
          "y": 143,
          "w": 200,
          "h": 0.4,
          "fontSize": 10,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e141",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 13,
          "y": 147.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RABATY"
        },
        {
          "id": "e142",
          "type": "field",
          "field": "discountTotal",
          "cardIndex": -1,
          "x": 13,
          "y": 155.1,
          "w": 92,
          "h": 7.2,
          "fontSize": 13,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e143",
          "type": "text",
          "field": null,
          "cardIndex": -1,
          "x": 105,
          "y": 147.8,
          "w": 92,
          "h": 4,
          "fontSize": 8,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "right",
          "content": "ŁĄCZNIE DO ZAPŁATY"
        },
        {
          "id": "e144",
          "type": "field",
          "field": "total",
          "cardIndex": -1,
          "x": 105,
          "y": 154.4,
          "w": 92,
          "h": 10.2,
          "fontSize": 17,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#16a34a",
          "bg": "transparent",
          "align": "right",
          "content": ""
        },
        {
          "id": "e173",
          "type": "image3d",
          "field": null,
          "cardIndex": 1,
          "x": 56.2,
          "y": 5,
          "w": 47.2,
          "h": 83.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e174",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 56.2,
          "y": 88.2,
          "w": 46.2,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e175",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 58.400000000000006,
          "y": 91.1,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e176",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 1,
          "x": 58.400000000000006,
          "y": 95,
          "w": 21.3,
          "h": 3.9,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e177",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 74.7,
          "y": 90.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e178",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 1,
          "x": 81.1,
          "y": 95,
          "w": 21.3,
          "h": 4.1,
          "fontSize": 4.3,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e179",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 58.400000000000006,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e180",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 1,
          "x": 64.2,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e181",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 78.5,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e182",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 1,
          "x": 85.35,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e183",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 58,
          "y": 114.3,
          "w": 42.5,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e184",
          "type": "rect",
          "field": null,
          "cardIndex": 1,
          "x": 58,
          "y": 116.1,
          "w": 18.6,
          "h": 6.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e185",
          "type": "text",
          "field": null,
          "cardIndex": 1,
          "x": 58.400000000000006,
          "y": 118.5,
          "w": 20.9,
          "h": 1.9,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e186",
          "type": "field",
          "field": "code",
          "cardIndex": 1,
          "x": 78.5,
          "y": 119.45,
          "w": 20.9,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e187",
          "type": "image3d",
          "field": null,
          "cardIndex": 2,
          "x": 107.4,
          "y": 5,
          "w": 47.2,
          "h": 83.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e188",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 107.4,
          "y": 88.2,
          "w": 46.2,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e189",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 109.60000000000001,
          "y": 91.1,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e190",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 2,
          "x": 109.60000000000001,
          "y": 95,
          "w": 21.3,
          "h": 3.9,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e191",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 125.9,
          "y": 90.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e192",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 2,
          "x": 132.3,
          "y": 95,
          "w": 21.3,
          "h": 4.1,
          "fontSize": 4.3,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e193",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 109.60000000000001,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e194",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 2,
          "x": 115.4,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e195",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 129.70000000000002,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e196",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 2,
          "x": 136.55,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e197",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 109.2,
          "y": 114.3,
          "w": 42.5,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e198",
          "type": "rect",
          "field": null,
          "cardIndex": 2,
          "x": 109.2,
          "y": 116.1,
          "w": 18.6,
          "h": 6.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e199",
          "type": "text",
          "field": null,
          "cardIndex": 2,
          "x": 109.60000000000001,
          "y": 118.5,
          "w": 20.9,
          "h": 1.9,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e200",
          "type": "field",
          "field": "code",
          "cardIndex": 2,
          "x": 129.70000000000002,
          "y": 119.45,
          "w": 20.9,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e201",
          "type": "image3d",
          "field": null,
          "cardIndex": 3,
          "x": 158.6,
          "y": 5,
          "w": 47.2,
          "h": 83.5,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e202",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 158.6,
          "y": 88.2,
          "w": 46.2,
          "h": 0.3,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#e5e7eb",
          "align": "left",
          "content": ""
        },
        {
          "id": "e203",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 160.79999999999998,
          "y": 91.1,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "RODZAJ"
        },
        {
          "id": "e204",
          "type": "field",
          "field": "shelfType",
          "cardIndex": 3,
          "x": 160.79999999999998,
          "y": 95,
          "w": 21.3,
          "h": 3.9,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e205",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 177.1,
          "y": 90.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "WYMIARY"
        },
        {
          "id": "e206",
          "type": "field",
          "field": "dimensions",
          "cardIndex": 3,
          "x": 183.5,
          "y": 95,
          "w": 21.3,
          "h": 4.1,
          "fontSize": 4.3,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e207",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 160.79999999999998,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR BOKÓW"
        },
        {
          "id": "e208",
          "type": "field",
          "field": "sideColor",
          "cardIndex": 3,
          "x": 166.6,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e209",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 180.9,
          "y": 106.9,
          "w": 21.3,
          "h": 2.1,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOLOR PÓŁEK"
        },
        {
          "id": "e210",
          "type": "field",
          "field": "shelfColor",
          "cardIndex": 3,
          "x": 187.75,
          "y": 110.4,
          "w": 17.1,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "sans-serif",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        },
        {
          "id": "e211",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 160.4,
          "y": 114.3,
          "w": 42.5,
          "h": 0.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f0efed",
          "align": "left",
          "content": ""
        },
        {
          "id": "e212",
          "type": "rect",
          "field": null,
          "cardIndex": 3,
          "x": 160.4,
          "y": 116.1,
          "w": 18.6,
          "h": 6.2,
          "fontSize": 4,
          "fontWeight": "normal",
          "fontFamily": "sans-serif",
          "color": "#111111",
          "bg": "#f3f4f6",
          "align": "left",
          "content": ""
        },
        {
          "id": "e213",
          "type": "text",
          "field": null,
          "cardIndex": 3,
          "x": 160.79999999999998,
          "y": 118.5,
          "w": 20.9,
          "h": 1.9,
          "fontSize": 4,
          "fontWeight": "600",
          "fontFamily": "sans-serif",
          "color": "#9ca3af",
          "bg": "transparent",
          "align": "left",
          "content": "KOD KONFIGURACYJNY"
        },
        {
          "id": "e214",
          "type": "field",
          "field": "code",
          "cardIndex": 3,
          "x": 180.9,
          "y": 119.45,
          "w": 20.9,
          "h": 3.5,
          "fontSize": 4,
          "fontWeight": "bold",
          "fontFamily": "monospace",
          "color": "#111827",
          "bg": "transparent",
          "align": "left",
          "content": ""
        }
      ]
    }
  }
};
